import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({subsets:['latin']})
export const metadata = {
  title: "Blogger",
  description: "Generated by Pranav ",
};
import Footer from "@/Components/Footer";
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      {/* <html lang="en">
        <body  className={inter.className} >
          {children}
        </body>
      </html> */}
        <html lang="en">
      <body className="flex flex-col min-h-screen">
        {/* Page content */}
        <main className="flex-grow">
          {children}
        </main>

        {/* Sticky Footer */}
        <Footer />
      </body>
    </html>
     </ClerkProvider>
  );
}

