import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css"
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({subsets:['latin']})
import Heade from "@/Components/extra/Heade";
export const metadata = {
  title: "CurioBlog",
  description: "Generated by Pranav ",
};
import Footer from "@/Components/Footer";
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Heade />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
     </ClerkProvider>
  );
}

