import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"
// import {
//   ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs';
const outfit = Outfit({subsets:['latin'],weight:["400","500","600","700"]})
export const metadata = {
  title: "Safarnama ",
  description: "Generated by Pranav ",
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
      <html lang="en">
        <body  className={outfit.className} >
          {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
          {children}
        </body>
      </html>
    // </ClerkProvider>
  );
}

